<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FlightController;
use App\Http\Controllers\AircraftController;
use App\Http\Controllers\AircraftImageController;
use App\Http\Controllers\AirlineMembershipController;
use App\Http\Controllers\NotificationsController;
use App\Http\Controllers\SetupController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PortalController;
use App\Http\Controllers\InviteCodeController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\NotamController;
use App\Http\Controllers\AirlineController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\SettingsController as AdminSettingsController;
use App\Http\Controllers\Admin\ActivityLogController;

// Setup wizard — only accessible before any user exists
Route::get('/setup', [SetupController::class, 'show'])->name('setup.index');
Route::post('/setup', [SetupController::class, 'store'])->name('setup.store');

// Global Welcome / Guest landing page
Route::get("/", [HomeController::class, "index"])->name("home");

// The Scribe API docs: a laravel-type Blade view (resources/views/scribe/index.blade.php,
// generated by `scribe:generate`) served publicly at /docs. Routing is manual (Scribe's
// own add_routes is off) so only this page is exposed - not the disabled Postman/OpenAPI
// spec routes. The base URL in the page resolves to the live APP_URL at render time.
Route::view('/docs', 'scribe.index')->name('scribe');

Route::middleware(['auth'])->group(function () {

    // -------------------------------------------------------------------------
    // Routes that do NOT require an active airline session
    // -------------------------------------------------------------------------

    // Airline Portal — join via invite code, always accessible
    Route::get('/portal', [PortalController::class, 'index'])->name('portal');
    Route::post('/portal/redeem', [PortalController::class, 'redeem'])
        ->middleware('verified')
        ->name('portal.redeem');

    // Found a new airline (access controlled in controller based on setting / Super-Admin role)
    Route::get('/airline/found', [AirlineController::class, 'found'])
        ->middleware('verified')
        ->name('airline.found');
    Route::post('/airline/found', [AirlineController::class, 'foundStore'])
        ->middleware('verified')
        ->name('airline.found.store');

    // Airline switcher — no active airline required (that's the point)
    Route::match(["GET", "POST"], "/user/switchactiveairline", [
        AirlineMembershipController::class,
        "changeActiveAirline",
    ])->middleware('verified')->name("changeactiveairline");

    // -------------------------------------------------------------------------
    // Instance Administration — Super-Admins only
    // -------------------------------------------------------------------------
    Route::prefix('admin')->name('admin.')->middleware('role:Super-Admin')->group(function () {
        Route::get('/', [AdminController::class, 'index'])->name('dashboard');

        // Instance settings — edit the key/value rows in the `settings` table
        Route::get('/settings', [AdminSettingsController::class, 'edit'])->name('settings.edit');
        Route::put('/settings', [AdminSettingsController::class, 'update'])->name('settings.update');

        // Activity log — browse the instance-wide audit trail
        Route::get('/activity', [ActivityLogController::class, 'index'])->name('activity.index');
    });

    // -------------------------------------------------------------------------
    // User account settings — profile, security, notification preferences
    // -------------------------------------------------------------------------
    Route::get('/settings', fn () => redirect()->route('settings.profile'))->name('settings');
    Route::get('/settings/profile', [SettingsController::class, 'profile'])->name('settings.profile');
    Route::get('/settings/security', [SettingsController::class, 'security'])->name('settings.security');

    // Two-factor management — each mutation re-checks the account password in the
    // controller (see SettingsController), so these do not rely on Fortify's own
    // POST/DELETE 2FA routes.
    Route::post('/settings/security/2fa/enable', [SettingsController::class, 'enableTwoFactor'])->name('settings.2fa.enable');
    Route::post('/settings/security/2fa/confirm', [SettingsController::class, 'confirmTwoFactor'])->name('settings.2fa.confirm');
    Route::post('/settings/security/2fa/recovery-codes', [SettingsController::class, 'regenerateRecoveryCodes'])->name('settings.2fa.recovery.regenerate');
    Route::post('/settings/security/2fa/recovery-codes/show', [SettingsController::class, 'revealRecoveryCodes'])->name('settings.2fa.recovery.show');
    Route::delete('/settings/security/2fa', [SettingsController::class, 'disableTwoFactor'])->name('settings.2fa.disable');

    Route::post('/settings/tokens', [SettingsController::class, 'storeToken'])->name('settings.tokens.store');
    Route::delete('/settings/tokens/{tokenId}', [SettingsController::class, 'destroyToken'])->name('settings.tokens.destroy');
    Route::get('/settings/notifications', [SettingsController::class, 'notifications'])->name('settings.notifications');
    Route::put('/settings/notifications', [SettingsController::class, 'updateNotifications'])->name('settings.notifications.update');
    Route::get('/settings/danger', [SettingsController::class, 'danger'])->name('settings.danger');
    Route::delete('/settings', [SettingsController::class, 'destroy'])->name('settings.destroy');

    // Dashboard — no airline middleware; controller handles the redirect to /portal itself
    Route::get("/user/dashboard", [DashboardController::class, "index"])->name("dashboard");

    // -------------------------------------------------------------------------
    // Routes that require an active airline session
    // -------------------------------------------------------------------------

    Route::middleware(['verified', 'airline'])->group(function () {

        // Invite code management (manager check enforced in controller)
        Route::get('/airline/invitecodes', [InviteCodeController::class, 'index'])->name('invitecodes.index');
        Route::post('/airline/invitecodes/generate', [InviteCodeController::class, 'generate'])->name('invitecodes.generate');
        Route::delete('/airline/invitecodes/{inviteCode}', [InviteCodeController::class, 'destroy'])->name('invitecodes.destroy');

        // Airline settings (manager check enforced in controller)
        Route::get('/airline/settings', [AirlineController::class, 'settings'])->name('airline.settings');
        Route::put('/airline/settings', [AirlineController::class, 'updateSettings'])->name('airline.settings.update');

        // Member management (manager check enforced in controller)
        Route::get('/airline/members', [MemberController::class, 'index'])->name('members.index');
        Route::put('/airline/members/{member}', [MemberController::class, 'update'])->name('members.update');
        Route::delete('/airline/members/{member}', [MemberController::class, 'destroy'])->name('members.destroy');
        Route::put('/airline/members/{member}/transfer-ownership', [MemberController::class, 'transferOwnership'])->name('members.transfer');

        // Announcements / NOTAMs (manager check enforced in controller)
        Route::get('/airline/announcements', [NotamController::class, 'index'])->name('notams.index');
        Route::post('/airline/announcements', [NotamController::class, 'store'])->name('notams.store');
        Route::put('/airline/announcements/{notam}', [NotamController::class, 'update'])->name('notams.update');
        Route::delete('/airline/announcements/{notam}', [NotamController::class, 'destroy'])->name('notams.destroy');

        // Flight Management
        Route::match(["GET", "POST"], "/user/flights/add", [FlightController::class, "addFlight"])->name("flightadd");
        Route::get("/user/flights/review", [FlightController::class, "listReviewFlights"])->name("flightreviewindex");
        Route::post("/user/flights/review/{flight}/accept", [FlightController::class, "acceptFlight"])->name("flightreviewaccept");
        Route::post("/user/flights/review/{flight}/reject", [FlightController::class, "rejectFlight"])->name("flightreviewreject");
        Route::get("/user/flights/list", [FlightController::class, "displayFlightsForUser"])->name("flightlist");
        Route::get("/user/flights/view/{flight}", [FlightController::class, "view"])->name("viewflight");

        // Crew Activity (airline-wide social flight feed)
        Route::get("/airline/activity", [FlightController::class, "displayCrewActivity"])->name("crewactivity");

        // Notifications
        Route::get("/user/notifications", [NotificationsController::class, "viewNotifications"])->name("usernotifications");
        Route::post("/user/notifications/{notification}/acknowledge", [NotificationsController::class, "acknowledge"])->name("notificationsacknowledge");
        Route::post("/user/notifications/acknowledge-all", [NotificationsController::class, "acknowledgeAll"])->name("notificationsacknowledgeall");

        // Fleet Management
        Route::match(["GET", "POST"], "/airline/fleetmanager", [AircraftController::class, "index"])->name("fleetmanager");
        Route::match(["GET", "POST"], "/airline/fleetmanager/create", [AircraftController::class, "create"])
            ->name("createaircraft")
            ->middleware(["can:add aircraft"]);
        Route::get("/airline/fleetmanager/view/{aircraft}", [AircraftController::class, "view"])->name("viewaircraft");
        Route::match(["GET", "POST"], "/airline/fleetmanager/edit/{aircraft}", [AircraftController::class, "edit"])
            ->name("editaircraft")
            ->middleware(["can:edit aircraft"]);
        Route::post("/airline/fleetmanager/retire/{aircraft}", [AircraftController::class, "retire"])
            ->name("retireaircraft")
            ->middleware(["can:edit aircraft"]);

        // Aircraft screenshot gallery. Authorization is enforced in the controller
        // via AircraftPolicy: `show` requires `view` (any member of the owning
        // airline), the mutating routes require `update` (per-airline Manager).
        Route::get("/airline/fleetmanager/view/{aircraft}/images/{image}", [AircraftImageController::class, "show"])
            ->name("aircraft.images.show")
            ->scopeBindings();
        Route::post("/airline/fleetmanager/view/{aircraft}/images", [AircraftImageController::class, "store"])
            ->name("aircraft.images.store");
        Route::patch("/airline/fleetmanager/view/{aircraft}/images/{image}/approve", [AircraftImageController::class, "approve"])
            ->name("aircraft.images.approve")
            ->scopeBindings();
        Route::patch("/airline/fleetmanager/view/{aircraft}/images/{image}/primary", [AircraftImageController::class, "setPrimary"])
            ->name("aircraft.images.primary")
            ->scopeBindings();
        Route::delete("/airline/fleetmanager/view/{aircraft}/images/{image}", [AircraftImageController::class, "destroy"])
            ->name("aircraft.images.destroy")
            ->scopeBindings();
    });
});
